In [16]:
import numpy as np

1. Buatlah Tensor di bawah ini dengan Python:

In [17]:
a = np.array([[23, 50], [7, 12]])
b = np.array([[57, 67], [99, 43]])
c = np.array([[75, 21], [57, 12]])
d = np.array([[87, 26], [18, 84]])

Tensor = np.array([a, b, c, d])
Tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [18]:
Tensor.shape

(4, 2, 2)

2. Lakukan perkalian terhadap matrix berikut:

In [20]:
A = np.array([[23, 50, 19], [7, 12, 109], [57, 67, 98]])
B = np.array([[17, 22, 19]])

A * B

array([[ 391, 1100,  361],
       [ 119,  264, 2071],
       [ 969, 1474, 1862]])

In [23]:
B @ A

array([[1628, 2387, 4583]])

3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

In [31]:
a = np.array([[23, 50, 19], [7, 12, 109], [57, 67, 98]])

#transpose
C = a.T
print(C)

#determinant
D = np.linalg.det(a)
print(D)

#inverse
E = np.linalg.inv(A)
print(E)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]
131344.0000000002
[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
