Linear Algebra Data
- scalar - array 0 dimension
- vector - array 1 dimension -> in pandas is series / 1 dimension
- matrix - array 2 dimension -> in pandas is dataframe / 2 dimension
- tensor - >= 3 dimension

- representative data -> data 3D


In [4]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
a.shape

(3, 3)

In [7]:
a[1, :] #akses index 1 semua column

array([4, 5, 6])

In [8]:
a[ :, -1]

array([3, 6, 9])

In [18]:
a[2, 1:]

array([8, 9])

In [9]:
np.diag(a)

array([1, 5, 9])

In [10]:
np.diag(np.diag(a))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [12]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
a @ np.eye(3) #tipe data dari int jadi float walaupun hasil kembali jadi matrix a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [16]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
b = np.array([[2, 0, 1], [4, 2, 1], [1, 0, 2]])
b.shape

(3, 3)

In [20]:
# vektor 1 dimensi
v = np.array([1,2,3])
v.shape

(3,)

In [21]:
# penjumlahan
# matrix -> skalar
10 + a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [22]:
# matrix -> matrix
a + b

array([[ 3,  2,  4],
       [ 8,  7,  7],
       [ 8,  8, 11]])

In [23]:
a + v

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [26]:
# pengurangan
# matrix -> skalar
10 - a

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [27]:
# matrix -> matrix
a - b

array([[-1,  2,  2],
       [ 0,  3,  5],
       [ 6,  8,  7]])

In [28]:
# pembagian
# matrix -> skalar
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [29]:
# matrix -> matrix
a / b

C:\Users\Kurim\AppData\Local\Temp\ipykernel_3512\3896035522.py:2: RuntimeWarning: divide by zero encountered in true_divide
  a / b


array([[0.5, inf, 3. ],
       [1. , 2.5, 6. ],
       [7. , inf, 4.5]])

In [30]:
# perkalian
# matrix -> matrix
M = np.array([[1, 2, 1],
              [4, 0, 2],
              [1, 0, 2]])

N = np.array([[2, 0],
              [1, 1],
              [4, 2]])

print(M)
print('')
print(N)

M @ N

[[1 2 1]
 [4 0 2]
 [1 0 2]]

[[2 0]
 [1 1]
 [4 2]]


array([[ 8,  4],
       [16,  4],
       [10,  4]])

In [31]:
N @ M

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [56]:
# transpose
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a = a.T

In [34]:
# inverse
b

array([[2, 0, 1],
       [4, 2, 1],
       [1, 0, 2]])

In [36]:
inv_b = np.linalg.inv(b)
inv_b

array([[ 0.66666667,  0.        , -0.33333333],
       [-1.16666667,  0.5       ,  0.33333333],
       [-0.33333333,  0.        ,  0.66666667]])

In [37]:
b @ inv_b

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.66533454e-16, 1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 0.00000000e+00, 1.00000000e+00]])

In [38]:
np.linalg.inv(n)

NameError: name 'n' is not defined

In [40]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
np.linalg.inv(a)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [42]:
X = np.array([[1, 2],
              [0, 2]])
X

array([[1, 2],
       [0, 2]])

In [43]:
np.linalg.det(X)

2.0

In [44]:
# inverse
np.linalg.inv(X)

array([[ 1. , -1. ],
       [ 0. ,  0.5]])

In [45]:
Y = np.array([[1, 2],
              [2, 4]])
Y

array([[1, 2],
       [2, 4]])

In [46]:
np.linalg.det(Y)

0.0

In [47]:
np.linalg.inv(Y)

LinAlgError: Singular matrix

In [49]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
np.linalg.det(a)

0.0

In [59]:
np.linalg.inv(a)

LinAlgError: Singular matrix

In [60]:
# Tensor
J = np.array([[1, 3, 4],
              [2, 6, 3]])

K = np.array([[1, 2, 4],
              [2, 9, 8]])

L = np.array([[1, 3, 4],
              [1, 1, 1]])

M = np.array([[5, 5, 5], 
              [2, 7, 2]])

In [61]:
Tensor = np.array([J, K, L, M])
Tensor

array([[[1, 3, 4],
        [2, 6, 3]],

       [[1, 2, 4],
        [2, 9, 8]],

       [[1, 3, 4],
        [1, 1, 1]],

       [[5, 5, 5],
        [2, 7, 2]]])

In [62]:
Tensor.shape

(4, 2, 3)

In [64]:
import matplotlib.pyplot as plt


In [ ]:
image = plt.imread('/content/2-4.jpg')
plt.imshow(image)
image.shape
image